name: Fetch Token Prices Every Minute

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every minute
  workflow_dispatch:

jobs:
  fetch-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Send Request to Update Tokens API
        run: |
          curl -X GET "https://www.sirennotify.com/api/updateTokens" \
            -H "Authorization: ${{ secrets.API_KEY }}" \
            -H "Content-Type: application/json"
