name: Fetch/Notify Token Prices Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  fetch-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Send Request to Update Tokens API
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl -X GET https://www.sirennotify.com/api/updateTokens -H "Authorization: ${API_KEY}" -H "Content-Type: application/json"
