name: Send Notifications Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-notifications:
    runs-on: ubuntu-latest

    steps:
      - name: Send Request to Check Price Alerts API
        run: |
          curl -X GET "https://www.sirennotify.com/api/checkPriceAlerts" \
            -H "Authorization: ${{ secrets.API_KEY }}" \
            -H "Content-Type: application/json"
